/********************************************************************
* libEvent.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error libEvent.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtablelibEvent();
extern void G__cpp_setup_inheritancelibEvent();
extern void G__cpp_setup_typetablelibEvent();
extern void G__cpp_setup_memvarlibEvent();
extern void G__cpp_setup_globallibEvent();
extern void G__cpp_setup_memfunclibEvent();
extern void G__cpp_setup_funclibEvent();
extern void G__set_cpp_environmentlibEvent();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "Event.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__libEventLN_TClass;
extern G__linked_taginfo G__libEventLN_TBuffer;
extern G__linked_taginfo G__libEventLN_TMemberInspector;
extern G__linked_taginfo G__libEventLN_TObject;
extern G__linked_taginfo G__libEventLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__libEventLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__libEventLN_TClonesArray;
extern G__linked_taginfo G__libEventLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__libEventLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__libEventLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__libEventLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__libEventLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__libEventLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__libEventLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__libEventLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__libEventLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__libEventLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__libEventLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__libEventLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__libEventLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__libEventLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__libEventLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__libEventLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__libEventLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__libEventLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__libEventLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__libEventLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__libEventLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__libEventLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__libEventLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__libEventLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__libEventLN_TParticle;
extern G__linked_taginfo G__libEventLN_TRef;
extern G__linked_taginfo G__libEventLN_HepMC;
extern G__linked_taginfo G__libEventLN_maplEstringcOunsignedsPlongcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOunsignedsPlonggRsPgRsPgR;
extern G__linked_taginfo G__libEventLN_HepMCcLcLGenParticle;
extern G__linked_taginfo G__libEventLN_HepMCcLcLGenEvent;
extern G__linked_taginfo G__libEventLN_HepMCcLcLGenVertex;
extern G__linked_taginfo G__libEventLN_vectorlEHepMCcLcLGenParticlemUcOallocatorlEHepMCcLcLGenParticlemUgRsPgR;
extern G__linked_taginfo G__libEventLN_reverse_iteratorlEvectorlEHepMCcLcLGenParticlemUcOallocatorlEHepMCcLcLGenParticlemUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__libEventLN_iteratorlEforward_iterator_tagcOHepMCcLcLGenParticlemUcOlongcOHepMCcLcLGenParticlemUmUcOHepMCcLcLGenParticlemUaNgR;
extern G__linked_taginfo G__libEventLN_iteratorlEforward_iterator_tagcOHepMCcLcLGenVertexmUcOlongcOHepMCcLcLGenVertexmUmUcOHepMCcLcLGenVertexmUaNgR;
extern G__linked_taginfo G__libEventLN_setlEconstsPHepMCcLcLGenVertexmUcOlesslEconstsPHepMCcLcLGenVertexmUgRcOallocatorlEconstsPHepMCcLcLGenVertexmUgRsPgR;
extern G__linked_taginfo G__libEventLN_maplEintcOHepMCcLcLGenVertexmUcOgreaterlEintgRcOallocatorlEpairlEconstsPintcOHepMCcLcLGenVertexmUgRsPgRsPgR;
extern G__linked_taginfo G__libEventLN_maplEintcOHepMCcLcLGenParticlemUcOlesslEintgRcOallocatorlEpairlEconstsPintcOHepMCcLcLGenParticlemUgRsPgRsPgR;
extern G__linked_taginfo G__libEventLN_maplEHepMCcLcLGenParticlemUcOintcOlesslEHepMCcLcLGenParticlemUgRcOallocatorlEpairlEHepMCcLcLGenParticlemUsPconstcOintgRsPgRsPgR;
extern G__linked_taginfo G__libEventLN_EventHeader;
extern G__linked_taginfo G__libEventLN_Event;

/* STUB derived class for protected member access */
